### PR TITLE
Refactor to shellfire

### PR DESCRIPTION
**Pull request by hatchan**
Thanks to @releasequeue for providing wercker with this rewrite.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Assuming this is tested, lgtm!

**Comment by ringods** [comment]
@hatchan looking forward to a release in the registry! :smile:

**Comment by nhuray** [comment]
@hatchan @ringods Hey guys, when do you plan to release version 2.0.0 ?

**Comment by ringods** [comment]
@nhuray I'm not more related to Wercker then you are: just a user. But via my company @releasequeue, I contributed to a reimplementation as a pure shell script. It is now up to @hatchan or @mies to finish this up and release in the registry. Looking forward to this myself. :smiley:

**Comment by hatchan** [comment]
Sorry for the delay. I was on vacation :) Thanks again for providing this @ringods

**Comment by ringods** [comment]
@hatchan there is still something wrong with the new version. I have this in my `wercker.yml`:

```
        - wercker/hipchat-notify@2.0.0:
            token: $HIPCHAT_TOKEN
            room-id: 821749
```

But when running the step, the `room-id` is expanded to this environment variable:

```
export WERCKER_HIPCHAT_NOTIFY_ROOM_ID="false"
```

Any idea where the mapping from option to environment variable goes wrong?

**Comment by hatchan** [comment]
Hmm I've seen this before, I'll create a ticket for it.

The workaround for now is to force it as a string, by wrapping it in quotes:

```
        - wercker/hipchat-notify@2.0.0:
            token: $HIPCHAT_TOKEN
            room-id: "821749"
```

**Comment by ringods** [comment]
Workaround in place and working. :+1:

**Pull request merged**
