### PR TITLE
Using curl instead of python.

### PR DESCRIPTION
**Pull request by ringods**
Not all Docker images (ewok) have python installed, so the HipChat notification has a much higher chance of working by using plain curl.

### CODE REVIEW

**Comment by ringods** [comment]
@hatchan can you have a look at my pull request and merge if OK?

**Comment by hatchan** [comment]
Sorry about that, totally forgot about this. Will look at it tomorrow, only issue I see now though is, that this solution doesn't encode json characters in the message (or other fields)

**Comment by ringods** [comment]
@hatchan you mean url-encoding the input?

**Comment by hatchan** [comment]
No the `WERCKER_HIPCHAT_NOTIFY_MESSAGE` if it contains a `"` or `\n` that will mess up the JSON, and will probably lead to invalid JSON being posted.

Let's say `WERCKER_HIPCHAT_NOTIFY_MESSAGE` contains just a `"`. The JSON that will be posted will be this:

```
{ .... "message": """ .... }
```

**Comment by ringods** [comment]
@hatchan I don't know if my original intent to drop Python makes sense then. Doing the JSON encoding in a shell script doesn't seem to be so easy. Let's forget this pull request for now.

**Comment by hatchan** [comment]
There is shellfire, which I have been meaning to check out for a while now:
https://github.com/shellfire-dev/shellfire That includes a json writer,
which only has a dependency on awk and should work on most cases.

**Comment by ringods** [comment]
@hatchan tnx for the pointer! I'll have a look at it and see if I can deliver the shell-based Hipchat notifier using it. I'll re-open the pull request when done.

**Comment by ringods** [comment]
@hatchan a small idea sync: write the HipChat notifier as a shellfire application in a separate (Wercker Github) repo, use [flatten](https://github.com/shellfire-dev/fatten) to create a standalone script. This standalone script is committed in this repo for the step. Or do we put everything in this repo?

**Comment by hatchan** [comment]
I was thinking of the following: 

- Write a shellfire-script in `wercker-step-hipchat-notify`
- During the wercker build phase, use fatten to create a single executable `run.sh`
- During deploy phase deploy this to wercker registry

**Comment by ringods** [comment]
@hatchan deal! I'll put the shellfire app in the `src` subfolder, add a `README.md` to it and update the `wercker.yml` file. I'll re-open the pull request once implemented.

**Comment by hatchan** [comment]
Awesome, looking forward to the pull request. 

Also take a look at this steps, to show you how we deal with compiling something during build and then using that during deploy to registry:

- https://github.com/wercker/step-shellcheck/blob/master/wercker.yml

**Comment by ringods** [comment]
@hatchan I notice that Wercker builded my initial pull request, but when I click through on the build url, it mentions that the page is private. Can you make that app public so I can followup on any possible build errors when I update the pull request?

**Comment by ringods** [comment]
@hatchan can you review the code in my fork? I had one of my developers work on it using shellfire.
https://github.com/ReleaseQueue/wercker-step-hipchat-notify

**Comment by ringods** [comment]
BTW, the project needs to be updated to Ewok. The build box referred to is a Docker image.

**Comment by mies** [comment]
@ringods @hatchan this looks good! But you still need to use a classic box as steps created with Ewok can't be deployed to the registry (yet)

**Comment by hatchan** [comment]
@ringods Sorry totally forgot about checking it out. Will take a look later today

**Comment by ringods** [comment]
@mies @hatchan I have invested the time to reimplement. Can Wercker finish this up with the box and deployment to the registry?

**Comment by hatchan** [comment]
I've created a new pr for this #7

**Pull request closed without merging**
